language: node_js
node_js:
  - "0.10"
git:
  submodules: false
before_script:
  - node_modules/.bin/jspm config registries.github.auth $GITHUB_AUTH
  - node_modules/.bin/jspm install --no-interaction
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
