language: node_js
node_js:
- '0.10'
git:
  submodules: false
before_script:
- node_modules/.bin/jspm config registries.github.auth $GITHUB_AUTH
- node_modules/.bin/jspm install --no-interaction
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  slack:
    secure: NzsP2t4VynKf/Vy+SeDUccxXLKmsf5HrcXRBG2X1ogQiYEK/6ZVBPEOQLY6jQZ0hYYEsMvVixgYGW9o2cEmtLWT10lwc/WeiofI+LIPdkXL3hyqE6n1BY80lTNc9EfeS0ADpSMqOiWh7RWOiy5bgd5DwPLvHKwFSlXYeMEmGm4Q=
